services:
  solar-control:
    build: .
    container_name: solar-control
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - API_KEY=${API_KEY:-change-me-please}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow access to host machine
    restart: unless-stopped
    networks:
      - solar-network

networks:
  solar-network:
    driver: bridge

